raw:
 semiconductor_quarterly: "../data/raw/semiconductor_quarterly.csv"

clean:
  semiconductor_quarterly: "../data/clean/semiconductor_quarterly_clean.csv"
  feature_engineering: "../data/clean/feature_selection.csv"
  ml1_results: "../data/clean/ml1_results.csv"

outputs:
  figures: "../data/graphs"